# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('uid', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
    ]
