# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uid',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
